Slave_sample: SLMP.o SOCKET.o TIMER.o CCIEF_BASIC_SLAVE.o SLMP_SERVER.o USER_SAMPLE.o
	gcc -o Slave_sample SLMP.o SOCKET.o TIMER.o CCIEF_BASIC_SLAVE.o SLMP_SERVER.o USER_SAMPLE.o

SLMP.o: /home/ユーザ名/CCIEF-BASIC_Slave/library/src/SLMP.c
	gcc -I/home/ユーザ名/CCIEF-BASIC_Slave/library/include -c /home/ユーザ名/CCIEF-BASIC_Slave/library/src/SLMP.c
SOCKET.o: /home/ユーザ名/CCIEF-BASIC_Slave/sample/src/SOCKET.c
	gcc -I/home/ユーザ名/CCIEF-BASIC_Slave/sample/include -c /home/ユーザ名/CCIEF-BASIC_Slave/sample/src/SOCKET.c
TIMER.o: /home/ユーザ名/CCIEF-BASIC_Slave/sample/src/TIMER.c
	gcc -I/home/ユーザ名/CCIEF-BASIC_Slave/sample/include -c /home/ユーザ名/CCIEF-BASIC_Slave/sample/src/TIMER.c
CCIEF_BASIC_SLAVE.o: /home/ユーザ名/CCIEF-BASIC_Slave/sample/src/CCIEF_BASIC_SLAVE.c
	gcc -I/home/ユーザ名/CCIEF-BASIC_Slave/sample/include -I/home/ユーザ名/CCIEF-BASIC_Slave/library/include -c /home/ユーザ名/CCIEF-BASIC_Slave/sample/src/CCIEF_BASIC_SLAVE.c
SLMP_SERVER.o: /home/ユーザ名/CCIEF-BASIC_Slave/sample/src/SLMP_SERVER.c
	gcc -I/home/ユーザ名/CCIEF-BASIC_Slave/sample/include -I/home/ユーザ名/CCIEF-BASIC_Slave/library/include -c /home/ユーザ名/CCIEF-BASIC_Slave/sample/src/SLMP_SERVER.c
USER_SAMPLE.o: /home/ユーザ名/CCIEF-BASIC_Slave/sample/src/USER_SAMPLE.c
	gcc -I/home/ユーザ名/CCIEF-BASIC_Slave/sample/include -I/home/ユーザ名/CCIEF-BASIC_Slave/library/include -c /home/ユーザ名/CCIEF-BASIC_Slave/sample/src/USER_SAMPLE.c