Master_sample: SLMP.o SOCKET.o TIMER.o CCIEF_BASIC_SLAVES.o CCIEF_BASIC_MASTER.o USER_SAMPLE.o
	gcc -o Master_sample SLMP.o SOCKET.o TIMER.o CCIEF_BASIC_SLAVES.o CCIEF_BASIC_MASTER.o USER_SAMPLE.o

SLMP.o: /home/ユーザ名/CCIEF-BASIC_Master/library/src/SLMP.c
	gcc -I/home/ユーザ名/CCIEF-BASIC_Master/library/include -c /home/ユーザ名/CCIEF-BASIC_Master/library/src/SLMP.c
SOCKET.o: /home/ユーザ名/CCIEF-BASIC_Master/sample/src/SOCKET.c
	gcc -I/home/ユーザ名/CCIEF-BASIC_Master/sample/include -c /home/ユーザ名/CCIEF-BASIC_Master/sample/src/SOCKET.c
TIMER.o: /home/ユーザ名/CCIEF-BASIC_Master/sample/src/TIMER.c
	gcc -I/home/ユーザ名/CCIEF-BASIC_Master/sample/include -c /home/ユーザ名/CCIEF-BASIC_Master/sample/src/TIMER.c
CCIEF_BASIC_SLAVES.o: /home/ユーザ名/CCIEF-BASIC_Master/sample/src/CCIEF_BASIC_SLAVES.c
	gcc -I/home/ユーザ名/CCIEF-BASIC_Master/sample/include -I/home/ユーザ名/CCIEF-BASIC_Master/library/include -c /home/ユーザ名/CCIEF-BASIC_Master/sample/src/CCIEF_BASIC_SLAVES.c
CCIEF_BASIC_MASTER.o: /home/ユーザ名/CCIEF-BASIC_Master/sample/src/CCIEF_BASIC_MASTER.c
	gcc -I/home/ユーザ名/CCIEF-BASIC_Master/sample/include -I/home/ユーザ名/CCIEF-BASIC_Master/library/include -c /home/ユーザ名/CCIEF-BASIC_Master/sample/src/CCIEF_BASIC_MASTER.c
USER_SAMPLE.o: /home/ユーザ名/CCIEF-BASIC_Master/sample/src/USER_SAMPLE.c
	gcc -I/home/ユーザ名/CCIEF-BASIC_Master/sample/include -I/home/ユーザ名/CCIEF-BASIC_Master/library/include -c /home/ユーザ名/CCIEF-BASIC_Master/sample/src/USER_SAMPLE.c